// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgXGUmc3253dO4l5Dpwxtk6BV3dindTCo',
    appId: '1:283979715570:web:47d19883b20c05e363d16b',
    messagingSenderId: '283979715570',
    projectId: 'vpn-server-picker',
    authDomain: 'vpn-server-picker.firebaseapp.com',
    storageBucket: 'vpn-server-picker.firebasestorage.app',
    measurementId: 'G-LC8945X64H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuQc8c7_O5jGqYvQyfb8uvM1vYg39h6EE',
    appId: '1:283979715570:android:c31166789416bdab63d16b',
    messagingSenderId: '283979715570',
    projectId: 'vpn-server-picker',
    storageBucket: 'vpn-server-picker.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxkhSJKxIHgo2USXklSVKX4LqzpilE4nQ',
    appId: '1:283979715570:ios:e6f7f57f70ac0e1b63d16b',
    messagingSenderId: '283979715570',
    projectId: 'vpn-server-picker',
    storageBucket: 'vpn-server-picker.firebasestorage.app',
    iosBundleId: 'com.example.vpnServerPicker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxkhSJKxIHgo2USXklSVKX4LqzpilE4nQ',
    appId: '1:283979715570:ios:e6f7f57f70ac0e1b63d16b',
    messagingSenderId: '283979715570',
    projectId: 'vpn-server-picker',
    storageBucket: 'vpn-server-picker.firebasestorage.app',
    iosBundleId: 'com.example.vpnServerPicker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgXGUmc3253dO4l5Dpwxtk6BV3dindTCo',
    appId: '1:283979715570:web:2cc45b76d94db09563d16b',
    messagingSenderId: '283979715570',
    projectId: 'vpn-server-picker',
    authDomain: 'vpn-server-picker.firebaseapp.com',
    storageBucket: 'vpn-server-picker.firebasestorage.app',
    measurementId: 'G-C34Z8FTC93',
  );
}
